// Turns tokens/<theme>.json (pulled from Figma) into registry/themes/<era>/<theme>.tokens.css.
// Usage: node scripts/build-tokens.ts [theme...]   (defaults to every known theme)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const THEMES: Record<string, string> = { aqua: "y2k", liquid: "now" };

type Value = string | number;
export interface TokenFile {
  collection: string;
  modes: string[];
  tokens: { name: string; type: "COLOR" | "FLOAT" | "STRING"; values: Record<string, Value> }[];
}

const FONT_FALLBACKS: Record<string, string> = {
  sans: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
  mono: "ui-monospace, SFMono-Regular, Menlo, monospace",
};
/** Close relatives to try before the generic stack (Lucida Grande is Mac only). */
const FONT_RELATIVES: Record<string, string> = {
  "Lucida Grande": '"Lucida Sans Unicode", "Lucida Sans", ',
};

export function cssVarName(token: string): string {
  const [group, ...rest] = token.split("/");
  const key = rest.join("-");
  return group === "color" || group === "motion" ? `--mi-${key}` : `--mi-${group}-${key}`;
}

export function cssValue(token: string, value: Value): string {
  const [group, key] = token.split("/");
  if (group === "font") return `"${value}", ${FONT_RELATIVES[value] ?? ""}${FONT_FALLBACKS[key!] ?? "sans-serif"}`;
  if (typeof value === "string") return value;
  if (group === "motion") return `${value}ms`;
  if (token === "glass/saturate") return `${value}%`;
  return `${value}px`;
}

export function tokensToCss(file: TokenFile): string {
  const sel = `[data-theme="${file.collection}"]`;
  const block = (mode: string, onlyChanged: boolean) =>
    file.tokens
      .filter((t) => !onlyChanged || t.values[mode] !== t.values.light)
      .map((t) => `  ${cssVarName(t.name)}: ${cssValue(t.name, t.values[mode]!)};`)
      .join("\n");
  const dark = block("dark", true);
  return `/* Generated by scripts/build-tokens.ts from tokens/${file.collection}.json (Figma). Do not edit by hand. */
${sel} {
  color-scheme: light;
${block("light", false)}
}

@media (prefers-color-scheme: dark) {
  ${sel}:not([data-mode="light"]) {
    color-scheme: dark;
${dark.replace(/^/gm, "  ")}
  }
}

${sel}[data-mode="dark"] {
  color-scheme: dark;
${dark}
}
`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const names = process.argv.slice(2).length ? process.argv.slice(2) : Object.keys(THEMES);
  for (const name of names) {
    const era = THEMES[name];
    if (!era) throw new Error(`Unknown theme "${name}". Add it to THEMES in scripts/build-tokens.ts.`);
    const file = JSON.parse(readFileSync(join(root, "tokens", `${name}.json`), "utf8")) as TokenFile;
    const out = join(root, "registry/themes", era, `${name}.tokens.css`);
    writeFileSync(out, tokensToCss(file));
    console.log(`wrote ${out}`);
  }
}
